sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    access-key-id: LTAI4G5Z
    access-key-secret: 5zL3z
    bucket-name: sky-take-out
    endpoint: oss-cn-shanghai.aliyuncs.com

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx6e6634fb0e9cf275
    secret: bf24981b8f87e7c5b6adf0dea23d93b6


